### ISSUE TITLE
Create Variant export to Defgen

### ISSUE THREAD

**Issue by thomasguignard** [mobidic/SEAL#53]

**Comment by Char-Al** [comment]
see 8de8a4d322b0d7acf3aa479f615ba65cff696d38

**Comment by Char-Al** [comment]
Working on exporting in ISO-8859-1 with CRCRLF line endings.
Current export lacks genotype info (column 'ETAT' for DefGen).

**Comment by Char-Al** [comment]
> Working on exporting in ISO-8859-1 with CRCRLF line endings. Current export lacks genotype info (column 'ETAT' for DefGen).

Won't fix that !
Export is now enable for DefGen
